apiVersion: v1
kind: Namespace
metadata:
  name: gati-lab

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  labels:
    app: www
spec:
  replicas: 1
  selector:
    matchLabels:
      name: www
  template:
    metadata:
      labels:
        name: www
    spec:
      containers:
      - name: www
        image: slaclab/cryo-recipes:20200514.0
        #image: slaclab/cryo-recipes:0.2-1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    app: www
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    name: www


